receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  logging:
    verbosity: detailed

  otlphttp/metrics:
    encoding: json
    endpoint: http://127.0.0.1:13030/otlp/original/json
 
  otlphttp/filtered_traces:
    encoding: json
    endpoint: http://127.0.0.1:13030/otlp/filtered/json

  otlphttp/filtered_logs:
    encoding: json
    endpoint: http://127.0.0.1:13030/otlp/filtered/json

  otlphttp/original_traces:
    encoding: json
    endpoint: http://127.0.0.1:13030/otlp/original/json

  otlphttp/original_logs:
    encoding: json
    endpoint: http://127.0.0.1:13030/otlp/original/json	
  prometheus:
    endpoint: 0.0.0.0:9464
  otlp/jaeger:
    endpoint: 127.0.0.1:14317
    tls :
      insecure : true


processors:
  batch:
  filter/logs:
    logs:
      log_record:
        - 'severity_number < 10'
        
  filter/error_spans:
    traces:
      span:
        - 'status.code != 2'

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp/original_logs]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/original_traces,otlp/jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/metrics, prometheus]

    logs/filtered:
      receivers: [otlp]
      processors: [batch, filter/logs]
      exporters: [otlphttp/filtered_logs]
      
    traces/error:
      receivers: [otlp]
      processors: [filter/error_spans]
      exporters: [otlphttp/filtered_traces]
